### ISSUE TITLE
Code does not work

### ISSUE THREAD

**Issue by MegaNoam** [LagBug/MapBuilder#3]
I used this utility and when I pasted the code into the intellij I got a weird error saying the method doesn't exist
![image](https://user-images.githubusercontent.com/18356302/65833163-bc811b80-e2d5-11e9-9af8-ac3cc4760c96.png)

I went to Spigot's libraries to see if the method existed, unfortunately I found out that it wasn't
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/map/MapView.html

I would like to get help with my problem 💜

**Comment by LagBug** [comment]
Hello, as stated overview, you must have spigot 1.14 or above as your library in your plugin.
